# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Python
on: [push, pull_request, merge_group]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Display Go version
        run: go version
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Display Python version
        run: python3 --version
      - uses: ./.github/actions/install-protoc
      - name: Install pandoc
        run: |
          set -e
          curl -fsSL --retry 5 --retry-delay 15 -o /tmp/pandoc.tar.gz https://github.com/jgm/pandoc/releases/download/$VERSION/pandoc-$VERSION-linux-amd64.tar.gz
          sudo tar -xvf /tmp/pandoc.tar.gz -C /usr/local --strip-components=1
          pandoc --version
        env:
          VERSION: 3.8.2
      - name: Install gapic-generator
        run: pip install gapic-generator==1.28.3
      - name: Install synthtool
        run: |
          pip install gcp-synthtool@git+https://github.com/googleapis/synthtool@5aa438a342707842d11fbbb302c6277fbf9e4655
      - name: Install nox
        run: |
          python -m pip install --upgrade setuptools pip wheel
          python -m pip install nox
      - name: Verify git is available
        run: git --version
      - name: Run internal/librarian/internal/python tests
        run: go test -race ./internal/librarian/internal/python
